version: '3.1'

services:
  raven-fornt:
    image: janikrabenstein:latest
    container_name: raven-forntend
    restart: always
    ports:
      - 80:80

  raven-back:
    image: nginx:latest
    container_name: raven-backend
    ports:
      - 81:80
    volumes:
      - ./raven-api:/var/www/html
      - ./raven-api-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    external_links:
      - php-fpm
      - db
    networks:
      raven_network:
        ipv4_address: 10.7.1.5

  php-fpm:
    image: fpmtest:latest
    container_name: raven-fpm
    volumes:
      - ./raven-api:/var/www/html
    external_links:
    - db
    networks:
      raven_network:
        ipv4_address: 10.7.1.4

  db:
    image: mariadb:latest
    container_name: raven-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    networks:
      raven_network:
        ipv4_address: 10.7.1.2

  phpmyadmin:
    image: phpmyadmin
    container_name: raven-phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    external_links:
      - db
    networks:
      raven_network:
        ipv4_address: 10.7.1.3


networks:
  raven_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.1.0/8
          gateway: 10.7.1.1
